### ISSUE TITLE
编译报错，蹲完整的编译方案

### ISSUE THREAD

**Issue by N0mi99** [yuebusao/jsonp-burp-killer#1]
使用jdk 11.0.12，编译报错20个：
`
BurpExtender.java:93: :  GBK Ĳӳַ (0x86)
                BurpExtender.this.mjSplitPane.add(BurpExtender.this.UscrollPane, "left"); // 结果?
                                                                                                 ^
BurpExtender.java:94: :  GBK Ĳӳַ (0x80)
                BurpExtender.this.mjSplitPane.add(BurpExtender.this.HjSplitPane, "right"); // request response??
                                                                                                               ^
BurpExtender.java:94: :  GBK Ĳӳַ (0xB7)
                BurpExtender.this.mjSplitPane.add(BurpExtender.this.HjSplitPane, "right"); // request response??
                                                                                                                 ^
BurpExtender.java:106: :  GBK Ĳӳַ (0x96)
//        String corswords = BurpExtender.this.textArea1.getText(); // 关键字读?
                                                                              ^
BurpExtender.java:107: :  GBK Ĳӳַ (0x96)
        String jsonpwords = BurpExtender.this.textArea2.getText(); // 关键字读?
                                                                             ^
BurpExtender.java:135: :  GBK Ĳӳַ (0xB4)
        List<String> request_header = analyzedIRequestInfo.getHeaders(); // 获取请求?
                                                                                   ^
BurpExtender.java:136: :  GBK Ĳӳַ (0x80)
        // 循环获取参数，判断类型，进行加密处理后，再构造新的参数，合并到新的请求包中??
                                                                   ^
BurpExtender.java:136: :  GBK Ĳӳַ (0x82)
        // 循环获取参数，判断类型，进行加密处理后，再构造新的参数，合并到新的请求包中??
                                                                    ^
BurpExtender.java:138: :  GBK Ĳӳַ (0x82)
        String firstrequest_header = request_header.get(0); //第一行请?
                                                                     ^
BurpExtender.java:149: :  GBK Ĳӳַ (0xA2)
                    firstheaders[1] = firstheaders[1].replace(jsonpword + "=", jsonpword + "=squirt1e"); // 原始请求含有callback，直接替?
                                                                                                                                    ^
BurpExtender.java:150: :  GBK Ĳӳַ (0x82)
                    break; //如果存在callback，直接替换并且break?
                                                           ^
BurpExtender.java:153: :  GBK Ĳӳַ (0x8C)
                        firstheaders[1] = firstheaders[1] + jsonpword+"=squirt1e"; // 含有参数的项??结尾
                                                                                                ^
BurpExtender.java:155: :  GBK Ĳӳַ (0x89)
                        firstheaders[1] = firstheaders[1] + "&"+jsonpword+"=squirt1e"; // 含有参数的项，含??且不??结尾
                                                                                                       ^
BurpExtender.java:155: :  GBK Ĳӳַ (0xAF)
                        firstheaders[1] = firstheaders[1] + "&"+jsonpword+"=squirt1e"; // 含有参数的项，含??且不??结尾
                                                                                                             ^
BurpExtender.java:167: :  GBK Ĳӳַ (0xA0)
                request_header.add("Origin: squirt1e.com"); // 请求头增?
                                                                      ^
BurpExtender.java:170: :  GBK Ĳӳַ (0x80)
            /*****************获取http request body 方法?**********************/
                                                       ^
BurpExtender.java:201: :  GBK Ĳӳַ (0x80)
            //优先?测jsonp漏洞
                  ^
BurpExtender.java:211: :  GBK Ĳӳַ (0x8B)
                        //修改Referer头检?
                                        ^
BurpExtender.java:213: :  GBK Ĳӳַ (0xB4)
                            request_header.add("Referer: test.top"); // 替换请求?
                                                                               ^
BurpExtender.java:302: :  GBK Ĳӳַ (0xB9)
        if (matcher.find()) { // 确保找到匹配?
                                           ^
20
`

**Comment by N0mi99** [comment]
大佬，求一份完整的编译方案，小白不会啊...

**Comment by yuebusao** [comment]
最新编译后版本已上传。
自行解决方案如下：
1. 开发环境使用JDK8，通过IDEA的maven插件编译。
2. pom.xml修改maven-compiler-plugin中的configuration里面加入<encoding>UTF-8</encoding>
